runtime: nodejs
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6

env_variables:
  EEP_DATABASE_ADMIN_NAME: "eep_admin"
  EEP_DATABASE_PASSWORD: "eep_password"
