runtime: nodejs
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6

env_variables:
  REACT_APP_GOOGLE_OAUTH_TOKEN: "46129005602-6ql2kc2m0eaftnam72glear0ltj82tc9.apps.googleusercontent.com"
  REACT_APP_BACKEND_URL: https://eep-backend.appspot.com

skip_files:
  package-lock.json
