#!/bin/bash

ECHO STARTING ECS SYSTEM
ECHO ECS MONITORING CONSOLE
java ECSConsole &
ECHO STARTING TEMPERATURE CONTROLLER CONSOLE
java TemperatureController &
ECHO STARTING HUMIDITY SENSOR CONSOLE
java HumidityController &
ECHO STARTING TEMPERATURE SENSOR CONSOLE
java TemperatureSensor &
ECHO STARTING HUMIDITY SENSOR CONSOLE
java HumiditySensor &